# Generated by Django 4.1 on 2025-03-27 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("flashcards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcardset",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="flashcard_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="flashcards.flashcardset",
            ),
        ),
    ]
