# Generated by Django 4.1 on 2025-04-25 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flashcards", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stability", models.FloatField(default=0.0)),
                ("difficulty", models.FloatField(default=5.0)),
                ("repetitions", models.IntegerField(default=0)),
                ("lapses", models.IntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("LRN", "Learning"),
                            ("REV", "Review"),
                            ("REL", "Relearning"),
                        ],
                        default="NEW",
                        max_length=3,
                    ),
                ),
                ("last_review_date", models.DateTimeField(blank=True, null=True)),
                ("next_review_date", models.DateTimeField(db_index=True)),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flashcards.flashcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_review_date"],
            },
        ),
        migrations.CreateModel(
            name="FlashcardSetProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_cards", models.PositiveIntegerField(default=0)),
                ("cards_reviewed", models.PositiveIntegerField(default=0)),
                ("cards_mastered", models.PositiveIntegerField(default=0)),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                (
                    "flashcard_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flashcards.flashcardset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyUserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("correct_reviews", models.PositiveIntegerField(default=0)),
                ("new_cards_studied", models.PositiveIntegerField(default=0)),
                ("cards_mastered", models.PositiveIntegerField(default=0)),
                ("streak", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "next_review_date"],
                name="flashcards__user_id_9bc91c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "flashcard"), name="unique_user_flashcard_review_state"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="flashcardsetprogress",
            unique_together={("user", "flashcard_set")},
        ),
        migrations.AlterUniqueTogether(
            name="dailyuserstats",
            unique_together={("user", "date")},
        ),
    ]
